version: '2'
services:
    db:
        image: mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=chouket
        volumes:
            - ./bdd:/var/lib/mysql
        ports:
            - 13306:3306
